"""Initial Migration

Revision ID: 37ec45dc66ca
Revises: 
Create Date: 2024-04-03 17:46:29.160084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ec45dc66ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('apologies',
    sa.Column('apology_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apology_text', sa.Text(), nullable=False),
    sa.Column('apology_created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_apologies_user_id_users')),
    sa.PrimaryKeyConstraint('apology_id')
    )
    op.create_table('apology_categories',
    sa.Column('apology_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apology_id'], ['apologies.apology_id'], name=op.f('fk_apology_categories_apology_id_apologies')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_apology_categories_category_id_categories')),
    sa.PrimaryKeyConstraint('apology_id', 'category_id')
    )
    op.create_table('intended_for',
    sa.Column('intended_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('event_location', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('apology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apology_id'], ['apologies.apology_id'], name=op.f('fk_intended_for_apology_id_apologies')),
    sa.PrimaryKeyConstraint('intended_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intended_for')
    op.drop_table('apology_categories')
    op.drop_table('apologies')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
